pipeline:
  name: java-poc
  identifier: javapoc
  projectIdentifier: jagruti_playground_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: GithubJagruti
        build: <+input>
  stages:
    - stage:
        name: build stage
        identifier: build_stage
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Build Java App
                  identifier: Build_Java
                  spec:
                    shell: Sh
                    command: |
                      echo "building java application"
                      mvn -B package --file zenzbg-template/greetings/pom.xml
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push Image
                  identifier: Build_Push_Image
                  spec:
                    connectorRef: Dockerhubjagruti
                    repo: 46990406/demo-harness
                    tags:
                      - latest
                    dockerfile: zenzbg-template/greetings/Dockerfile
                    context: zenzbg-template/greetings
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Bash
                    command: |-
                      echo "$key" > key2.pem
                      chmod 400 key2.pem
                      ssh -i key2.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null vm@20.244.32.79
                      whoami
                      curl ifconfig.io
                      docker -v
                      cat /etc/os-release
                      pwd
                      echo "Pulling image "
                      sudo docker pull 46990406/demo-harness:latest
                      sudo docker run -d --name demo-harness -p 8080:8080 46990406/demo-harness:latest
                    envVariables:
                      key: <+secrets.getValue("azure-key-file")>
        description: ""
    - stage:
        name: Deploy
        identifier: Deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Ssh
          service:
            serviceRef: javaappservice
          environment:
            environmentRef: envjavaapp
            deployToAll: false
            infrastructureDefinitions:
              - identifier: azurevmtypeinfra
          execution:
            steps:
              - step:
                  type: ShellScriptProvision
                  name: ShellScriptProvision_1
                  identifier: ShellScriptProvision_1
                  spec:
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo "$key" > key2.pem
                          chmod 400 key2.pem
                          ssh -i key2.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null vm@20.244.32.79
                          whoami
                          curl ifconfig.io
                          docker -v
                          cat /etc/os-release
                          pwd
                          echo "Pulling image "
                          sudo docker pull 46990406/demo-harness:latest
                          sudo docker run -d --name demo-harness -p 8080:8080 46990406/demo-harness:latest
                    environmentVariables:
                      - name: key
                        type: String
                        value: <+secrets.getValue("azure-key-file")>
                  timeout: 10m
                  failureStrategies:
                    - onFailure:
                        errors:
                          - AllErrors
                        action:
                          type: Abort
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsFailure
  allowStageExecutions: true
