pipeline:
  name: java-poc
  identifier: javapoc
  projectIdentifier: jagruti_playground_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: GithubJagruti
        build: <+input>
  stages:
    - stage:
        name: build stage
        identifier: build_stage
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Build Java App
                  identifier: Build_Java
                  spec:
                    shell: Sh
                    command: |
                      echo "building java application"
                      mvn -B package --file zenzbg-template/greetings/pom.xml
              - parallel:
                  - step:
                      type: Owasp
                      name: Run OWASP Scan
                      identifier: Owasp_Scan
                      spec:
                        target:
                          detection: auto
                          type: repository
                        mode: orchestration
                        config: default
                  - step:
                      type: OsvScanner
                      name: Run OSV Scan
                      identifier: Osv_Scan
                      spec:
                        target:
                          detection: auto
                          type: repository
                        mode: orchestration
                        config: default
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push Image
                  identifier: Build_Push_Image
                  spec:
                    connectorRef: Dockerhubjagruti
                    repo: 46990406/demo-harness
                    tags:
                      - latest
                    dockerfile: zenzbg-template/greetings/Dockerfile
                    context: zenzbg-template/greetings
              - step:
                  type: Run
                  name: Deploy on Docker Container
                  identifier: Deploy_Docker
                  spec:
                    shell: Sh
                    command: |
                      echo "Pulling image and running container..."
                      docker pull 46990406/demo-harness:latest
                      docker stop demo-harness || true
                      docker rm demo-harness || true
                      docker run -d --name demo-harness -p 8080:8080 46990406/demo-harness:latest
